# Generated by Django 3.1.2 on 2020-11-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProBi',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(help_text='项目名字', max_length=20, unique=True, verbose_name='项目名字')),
                ('p_tester', models.CharField(max_length=5)),
                ('p_rd', models.CharField(max_length=5)),
                ('p_desc', models.TextField(blank=True, verbose_name='项目简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新记录时间')),
            ],
            options={
                'verbose_name': '项目表',
                'db_table': 'project_biao',
            },
        ),
    ]
